services:
  micro-mockba-asset-futures-bot:
    image: andresdom2004/micro-mockba-asset-futures-bot:latest
    container_name: micro-mockba-asset-futures-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-apolo-asset
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_LIFECYCLE_HOOKS=true
      - WATCHTOWER_LABEL_ENABLE=true