services:
  micro-mockba-apolo-futures-bot:
    image: andresdom2004/micro-mockba-apolo-futures-bot:latest
    container_name: micro-mockba-apolo-futures-bot
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: always
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./llm_prompt_template.txt:/app/futures_perps/trade/apolo/llm_prompt_template.txt
    depends_on:
      - redis-apolo
    networks:
      - mockba-apolo-net

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-apolo
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_LIFECYCLE_HOOKS=true
      - WATCHTOWER_LABEL_ENABLE=true
    networks:
      - mockba-apolo-net

  redis-apolo:
    image: redis:latest
    container_name: redis-mockba-apolo
    restart: always
    ports:
      - "6393:6379"
    volumes:
      - redis_apolo_data:/data
    networks:
      - mockba-apolo-net

volumes:
  redis_apolo_data:

networks:
  mockba-apolo-net:
    driver: bridge